# agents/report_generator.py
# Save this as: agents/report_generator.py
# This generates a professional formatted .txt file from meeting data

import os
from datetime import datetime


def format_duration(seconds: float) -> str:
    """Convert seconds to human readable duration."""
    if seconds < 60:
        return f"{int(seconds)} seconds"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    if secs == 0:
        return f"{minutes} minutes"
    return f"{minutes} minutes {secs} seconds"


def generate_meeting_report(
    transcript: str,
    summary: str,
    tasks: list,
    report: str,
    language: str = "en",
    duration: float = 0.0,
    meeting_id: int = None,
) -> str:
    """
    Generates a professional formatted meeting report as a string.
    Can be saved as a .txt file or returned directly.

    Args:
        transcript : raw transcript text
        summary    : Agent 1 output
        tasks      : Agent 2 output (list of dicts)
        report     : Agent 3 output
        language   : "en" or "am"
        duration   : recording duration in seconds
        meeting_id : database meeting ID

    Returns:
        str: formatted report text
    """

    now = datetime.now()
    date_str = now.strftime("%B %d, %Y")
    time_str = now.strftime("%I:%M %p")
    lang_label = "English" if language == "en" else "Amharic (አማርኛ)" if language == "am" else "Auto-detected"

    divider   = "═" * 55
    thin_line = "─" * 55

    lines = []

    # ── HEADER ──────────────────────────────────────────
    lines.append(divider)
    lines.append("         MEETING TRANSCRIPT & REPORT")
    lines.append("            Generated by MeetingMind AI")
    lines.append(divider)
    lines.append(f"  Date       : {date_str}")
    lines.append(f"  Time       : {time_str}")
    lines.append(f"  Language   : {lang_label}")
    lines.append(f"  Duration   : {format_duration(duration)}")
    if meeting_id:
        lines.append(f"  Meeting ID : #{meeting_id}")
    lines.append(f"  Processed  : MeetingMind AI v1.0 — Groq LLaMA 3.3 70B")
    lines.append(divider)
    lines.append("")

    # ── TRANSCRIPT ──────────────────────────────────────
    lines.append("TRANSCRIPT")
    lines.append(thin_line)
    lines.append("")
    # Word wrap transcript at 55 chars
    words = transcript.strip().split()
    current_line = ""
    for word in words:
        if len(current_line) + len(word) + 1 <= 55:
            current_line += (" " if current_line else "") + word
        else:
            if current_line:
                lines.append(current_line)
            current_line = word
    if current_line:
        lines.append(current_line)
    lines.append("")
    lines.append(divider)
    lines.append("")

    # ── SUMMARY ─────────────────────────────────────────
    lines.append("SUMMARY")
    lines.append(thin_line)
    lines.append("")
    for summary_line in summary.strip().split("\n"):
        lines.append(summary_line)
    lines.append("")
    lines.append(divider)
    lines.append("")

    # ── ACTION ITEMS ────────────────────────────────────
    lines.append("ACTION ITEMS")
    lines.append(thin_line)
    lines.append("")
    if tasks:
        for i, task in enumerate(tasks, 1):
            task_name = task.get("task", "Unknown task")
            owner = task.get("owner", "Unknown")
            deadline = task.get("deadline", "No deadline")
            status = task.get("status", "Pending")
            lines.append(f"  {i}. {task_name}")
            lines.append(f"     Owner    : {owner}")
            lines.append(f"     Deadline : {deadline}")
            lines.append(f"     Status   : {status}")
            lines.append("")
    else:
        lines.append("  No action items extracted.")
        lines.append("")
    lines.append(divider)
    lines.append("")

    # ── FOLLOW-UP REPORT ────────────────────────────────
    lines.append("FOLLOW-UP REPORT")
    lines.append(thin_line)
    lines.append("")
    for report_line in report.strip().split("\n"):
        if report_line.strip() and report_line != "FOLLOW-UP REPORT":
            lines.append(f"  {report_line}")
    lines.append("")
    lines.append(divider)
    lines.append("")

    # ── FOOTER ──────────────────────────────────────────
    lines.append("         Generated by MeetingMind AI")
    lines.append(f"         {date_str} at {time_str}")
    lines.append("         github.com/Yonatan8475/gemini-multi-agent")
    lines.append(divider)

    return "\n".join(lines)


def save_report_to_file(
    report_text: str,
    meeting_id: int = None,
    output_dir: str = "reports"
) -> str:
    """
    Saves the formatted report to a .txt file.

    Args:
        report_text : the formatted report string
        meeting_id  : used in filename
        output_dir  : folder to save reports in

    Returns:
        str: path to the saved file
    """
    # Create reports directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Generate filename
    now = datetime.now()
    timestamp = now.strftime("%Y%m%d_%H%M%S")
    if meeting_id:
        filename = f"meeting_{meeting_id}_{timestamp}.txt"
    else:
        filename = f"meeting_{timestamp}.txt"

    filepath = os.path.join(output_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report_text)

    return filepath


# ── TEST ──────────────────────────────────────────────
if __name__ == "__main__":
    test_transcript = "John will build the API backend by Friday. Sarah will clean the dataset by Wednesday. Mike will prepare documentation by Thursday."
    test_summary = "Key Points:\n- API backend assigned to John\n- Dataset cleaning assigned to Sarah\n- Documentation assigned to Mike\n\nDecisions Made:\n- All tasks due by end of week"
    test_tasks = [
        {"task": "Build API backend", "owner": "John", "deadline": "Friday", "status": "Pending"},
        {"task": "Clean dataset", "owner": "Sarah", "deadline": "Wednesday", "status": "Pending"},
        {"task": "Prepare documentation", "owner": "Mike", "deadline": "Thursday", "status": "Pending"},
    ]
    test_report = "FOLLOW-UP REPORT\n1. Build API backend → John → Due: Friday → Status: Pending\n2. Clean dataset → Sarah → Due: Wednesday → Status: Pending\n3. Prepare documentation → Mike → Due: Thursday → Status: Pending"

    report = generate_meeting_report(
        transcript=test_transcript,
        summary=test_summary,
        tasks=test_tasks,
        report=test_report,
        language="en",
        duration=204,
        meeting_id=1
    )

    print(report)

    # Save to file
    path = save_report_to_file(report, meeting_id=1)
    print(f"\nSaved to: {path}")